/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      animation: {
        'spin-slow': 'spin 3s linear infinite',
      },
      gridTemplateColumns: {
        '13': 'repeat(13, minmax(0, 1fr))',
        '14': 'repeat(14, minmax(0, 1fr))',
        '15': 'repeat(15, minmax(0, 1fr))',
        '16': 'repeat(16, minmax(0, 1fr))',
      },
      // Optional: Add spans if you need an item to span 14 or 15 cols
      gridColumn: {
        'span-13': 'span 13 / span 13',
        'span-14': 'span 14 / span 14',
        'span-15': 'span 15 / span 15',
        'span-16': 'span 16 / span 16',
      },
      colors: {
        purple: {
          50: '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7157e4',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          950: '#2e1065',
        },
        "on-secondary": "#11362d",
        "primary-fixed-dim": "#00e383",
        "tertiary-fixed": "#e5e2e1",
        "secondary": "#a8cfc1",
        "on-tertiary": "#313030",
        "tertiary": "#fefbfa",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-container": "#636262",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#c3ebdd",
        "on-secondary-container": "#9ac1b3",
        "primary-container": "#00ff94",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#2c5045",
        "on-primary": "#00391d",
        "on-background": "#e5e2e1",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-error": "#690005",
        "secondary-fixed-dim": "#a8cfc1",
        "surface-variant": "#353534",
        "on-primary-fixed-variant": "#00522c",
        "surface": "#131313",
        "on-secondary-fixed": "#002019",
        "surface-bright": "#3a3939",
        "on-tertiary-fixed": "#1c1b1b",
        "tertiary-container": "#e1dede",
        "primary-fixed": "#5bffa1",
        "on-surface": "#e5e2e1",
        "inverse-primary": "#006d3c",
        "on-primary-container": "#00713f",
        "on-secondary-fixed-variant": "#294d43",
        "on-tertiary-fixed-variant": "#474746",
        "background": "#131313",
        "outline": "#849586",
        "inverse-on-surface": "#313030",
        "primary": "#f2fff1",
        "outline-variant": "#3b4b3e",
        "surface-container-low": "#1c1b1b",
        "surface-dim": "#131313",
        "surface-tint": "#00e383",
        "error-container": "#93000a",
        "surface-container": "#201f1f",
        "on-surface-variant": "#b9cbbb",
        "on-primary-fixed": "#00210e"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        "headline": ["Anton", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body": ["Geist", "sans-serif"]
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};