export const NotificationTypes = {
  COMMENT: "COMMENT",

  COMMENT_CREATED: "COMMENT_CREATED",
  POST_CREATED: "POST_CREATED",

  MENTION_COMMENT: "MENTION_COMMENT",
  MENTION_POST: "MENTION_POST",

  INTERACT_COMMENT: "INTERACT_COMMENT",
  INTERACT_POST: "INTERACT_POST",

  LIKE: "LIKE",
  FOLLOW: "FOLLOW",
  WISHLIST: "WISHLIST",
};